config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  namespace :api do
    resources :bins, only: [:create]

    namespace :bins do
      resources :units, only: [:show]
      resources :collections, only: [:show]
    end
  end

  # ALIAS

  get '/:id',   to: 'api/bins/units#show'
  get '/c/:id', to: 'api/bins/collections#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bin.rb
class Bin
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  has_one :bin_info, dependent: :destroy
  belongs_to :bin_collection, optional: true

  def requested!
    bin_info.update(request_count: bin_info.request_count += 1)
  end


  def as_json(*)
    super.except('_id', 'id', 'bin_collection_id')
  end
end

app/models/bin_collection.rb
class BinCollection
  include Mongoid::Document

  has_many :bins

  field :name, type: String
  field :ip_address, type: String
  field :request_count, type: Integer, default: 0
  field :created_at, type: DateTime, default: DateTime.current
  field :updated_at, type: DateTime, default: DateTime.current

  def requested!
    update(request_count: self.request_count += 1)
  end
end

app/models/bin_info.rb
class BinInfo
  include Mongoid::Document

  belongs_to :bin

  field :ip_address, type: String
  field :request_count, type: Integer, default: 0
  field :created_at, type: DateTime, default: Time.current
  field :updated_at, type: DateTime, default: Time.current
end

app/controllers/api/bins/collections_controller.rb
class Api::Bins::CollectionsController < Api::BinsController
  def show
    @bins = Search::BinCollection.new(params).invoke
    @bins.last.bin_collection.requested! if @bins.any?

    respond_to do |format|
      format.json { render json: @bins.as_json, status: :ok }
      format.html { render json: @bins.as_json, status: :ok }
    end
  end

  def search_engine
    @search_engine ||= Search::BinCollection.new(params).invoke
  end
end

app/controllers/api/bins/units_controller.rb
class Api::Bins::UnitsController < Api::BinsController
  def show
    @bin = Bin.find(params[:id])
    @bin.requested!

    respond_to do |format|
      format.json { render json: @bin.as_json, status: :ok }
      format.html { render json: @bin.as_json, status: :ok }
    end
  end
end

app/controllers/api/bins_controller.rb
class Api::BinsController < ApiController
  def create
    @result = Mutators::Bin::Create.new(new_bin_params, ip_address: request.ip).invoke

    response_for(@result)
  end

  private

  def new_bin_params
    BinParamsArranger.new(params).prepare
  end

  def response_for(item)
    url = generate_url

    respond_to do |format|
      if item.errors.none?
        format.json { render json: { url: url }, status: :created }
        format.html { render json: { url: url }, status: :created }
      else
        format.json { render json: item.errors, status: :unprocessable_entity }
        format.html { render json: item.errors, status: :unprocessable_entity }
      end
    end
  end

  def generate_url
    case @result.class
    when Bin
      api_bins_unit_url(@result)
    when BinCollection
      api_bins_collection_url(@result)
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/api/bins_helper.rb
module Api::BinsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/bins/_form.html.slim
= form_tag(api_bins_path, { class: 'bins-create-form', id: 'bins-form' }) do
  = text_area_tag :content
  div
    br
    = submit_tag 'Create', data: { disable_with: false }, class: 'btn'

app/views/home/index.html.slim
.home-content-wrapper
  .links
    => link_to('Doc', 'https://github.com/OrestF/flexible_json_storage/blob/master/README.md', target: '_blank')
    | &nbsp;
    a.toggle-ballon-animation href="#"
      |  Animation on/off

  h1.home-page-title
    | Flexible json storage

  .home-page-desc
    | Store and retrieve your JSON data

  .bins-form-wrapper
    = render 'home/bins/form'

.balloon-animation-wrapper
  .clouds
    .cloud
    .cloud
    .cloud
    .cloud
    .cloud
    .cloud
    .cloud
    .cloud
    .cloud
    .cloud
  .balloon
    .envelope
    .basket

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | FlexibleJsonStorage
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield